/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TagsView: typeof import('./components/TagsView.vue')['default']
  }
}
